version: '3.8'

services:
  postgres:  # Общая БД для всех сервисов
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 297032
      POSTGRES_DB: ordersKafka  # Одна БД, но сервисы используют разные таблицы
    ports:
      - "5432:5432"

  microservice1:
    build: ./KafkaOrders/Orders  # Путь к папке с Dockerfile сервиса 1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ordersKafka
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 297032
    depends_on:
      - postgres

  microservice2:
    build: ./KafkaOrders/Payment  # Путь к папке с Dockerfile сервиса 2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ordersKafka
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 297032
    depends_on:
      - postgres

  kafka:  # Kafka в той же сети
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"